# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DateEditDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Date_Edit(object):
    def setupUi(self, Dialog_Date_Edit):
        Dialog_Date_Edit.setObjectName("Dialog_Date_Edit")
        Dialog_Date_Edit.resize(577, 273)
        Dialog_Date_Edit.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Date_Edit)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calendarWidget_a = QtWidgets.QCalendarWidget(Dialog_Date_Edit)
        self.calendarWidget_a.setObjectName("calendarWidget_a")
        self.horizontalLayout.addWidget(self.calendarWidget_a)
        self.calendarWidget_b = QtWidgets.QCalendarWidget(Dialog_Date_Edit)
        self.calendarWidget_b.setObjectName("calendarWidget_b")
        self.horizontalLayout.addWidget(self.calendarWidget_b)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_Date_Edit)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_Date_Edit)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Date_Edit)

    def retranslateUi(self, Dialog_Date_Edit):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Date_Edit.setWindowTitle(_translate("Dialog_Date_Edit", "时间范围选择"))
