# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_login.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Login(object):
    def setupUi(self, Dialog_Login):
        Dialog_Login.setObjectName("Dialog_Login")
        Dialog_Login.resize(400, 250)
        Dialog_Login.setMinimumSize(QtCore.QSize(400, 250))
        Dialog_Login.setMaximumSize(QtCore.QSize(400, 250))
        self.label_login = QtWidgets.QLabel(Dialog_Login)
        self.label_login.setGeometry(QtCore.QRect(50, 10, 277, 50))
        self.label_login.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(43)
        self.label_login.setFont(font)
        self.label_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login.setObjectName("label_login")
        self.btn_login = QtWidgets.QPushButton(Dialog_Login)
        self.btn_login.setGeometry(QtCore.QRect(70, 200, 233, 30))
        self.btn_login.setMinimumSize(QtCore.QSize(233, 30))
        self.btn_login.setMaximumSize(QtCore.QSize(233, 30))
        self.btn_login.setObjectName("btn_login")
        self.layoutWidget = QtWidgets.QWidget(Dialog_Login)
        self.layoutWidget.setGeometry(QtCore.QRect(71, 160, 245, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_capcha = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_capcha.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_capcha.setText("")
        self.lineEdit_capcha.setObjectName("lineEdit_capcha")
        self.horizontalLayout.addWidget(self.lineEdit_capcha)
        self.label_captcha = QtWidgets.QLabel(self.layoutWidget)
        self.label_captcha.setMinimumSize(QtCore.QSize(75, 32))
        self.label_captcha.setMaximumSize(QtCore.QSize(75, 32))
        self.label_captcha.setText("")
        self.label_captcha.setObjectName("label_captcha")
        self.horizontalLayout.addWidget(self.label_captcha)
        self.pushButton_shuaxin = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_shuaxin.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_shuaxin.setObjectName("pushButton_shuaxin")
        self.horizontalLayout.addWidget(self.pushButton_shuaxin)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog_Login)
        self.layoutWidget1.setGeometry(QtCore.QRect(71, 120, 231, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_password = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_password.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_2.addWidget(self.lineEdit_password)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog_Login)
        self.layoutWidget2.setGeometry(QtCore.QRect(71, 77, 231, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_name = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_name.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_3.addWidget(self.lineEdit_name)

        self.retranslateUi(Dialog_Login)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Login)

    def retranslateUi(self, Dialog_Login):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Login.setWindowTitle(_translate("Dialog_Login", "车间生产数据统计工具"))
        self.label_login.setText(_translate("Dialog_Login", "登录"))
        self.btn_login.setText(_translate("Dialog_Login", "登录"))
        self.label_3.setText(_translate("Dialog_Login", "验证码"))
        self.lineEdit_capcha.setPlaceholderText(_translate("Dialog_Login", "请输入验证码"))
        self.pushButton_shuaxin.setText(_translate("Dialog_Login", "刷新"))
        self.label_2.setText(_translate("Dialog_Login", "密  码"))
        self.lineEdit_password.setText(_translate("Dialog_Login", "hbwj@2020"))
        self.lineEdit_password.setPlaceholderText(_translate("Dialog_Login", "请输入密码"))
        self.label.setText(_translate("Dialog_Login", "用户名"))
        self.lineEdit_name.setText(_translate("Dialog_Login", "hbwj@zhedao.net"))
        self.lineEdit_name.setPlaceholderText(_translate("Dialog_Login", "请输用户名"))
